--liquibase formatted sql
--changeset stockAndWarehouseMaster tfgAlberto:tablas_auxiliares

CREATE TABLE ALAMACENES_CAMIONES (
    ALMACEN_ID numeric (4,0) NOT NULL,
    CAMION_ID numeric (4,0) NOT NULL,
    PRIMARY KEY (ALMACEN_ID, CAMION_ID),
  	FOREIGN KEY (ALMACEN_ID) REFERENCES ALMACENES(ID),
  	FOREIGN KEY (CAMION_ID) REFERENCES CAMIONES(ID)
);


CREATE TABLE ALMACENES_PRODUCTOS (
    ALMACEN_ID numeric (4,0) NOT NULL,
    PRODUCTO_ID numeric (4,0) NOT NULL,
    STOCK integer NOT NULL,
    PRIMARY KEY (ALMACEN_ID, PRODUCTO_ID),
  	FOREIGN KEY (ALMACEN_ID) REFERENCES ALMACENES(ID),
  	FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);


CREATE TABLE PEDIDOS_PRODUCTOS_ALMACENES (
    PEDIDO_ID numeric (4,0) NOT NULL,
    ALMACEN_ID numeric (4,0) NOT NULL,
    PRODUCTO_ID numeric (4,0) NOT NULL,
    CANTIDAD numeric NOT NULL,
    PRIMARY KEY (PEDIDO_ID, PRODUCTO_ID),
  	FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID),
  	FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID),
  	FOREIGN KEY (ALMACEN_ID) REFERENCES ALMACENES(ID)
);
